#import "MobileTrackerBridge.h"
#import <React/RCTLog.h>

// Import the Swift module - this will be generated by Xcode
#if __has_include("MobileTracker-Swift.h")
#import "MobileTracker-Swift.h"
#else
// For standalone compilation, we'll use a forward declaration
@import MobileTracker;
#endif

@implementation MobileTrackerBridge

RCT_EXPORT_MODULE(MobileTrackerBridge)

// Initialize the SDK
RCT_EXPORT_METHOD(initialize:(NSDictionary *)config
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
    @try {
        // Extract configuration values
        NSString *brandId = config[@"apiKey"]; // Brand ID passed as apiKey
        NSString *apiUrl = config[@"endpoint"];
        NSString *xApiKey = config[@"x_api_key"];
        BOOL debug = [config[@"debug"] boolValue];
        
        if (!brandId || brandId.length == 0) {
            reject(@"INVALID_CONFIG", @"Brand ID (apiKey) is required", nil);
            return;
        }
        
        if (!apiUrl || apiUrl.length == 0) {
            reject(@"INVALID_CONFIG", @"API URL (endpoint) is required", nil);
            return;
        }
        
        // Create TrackerConfig
        TrackerConfig *trackerConfig = [[TrackerConfig alloc] initWithDebug:debug
                                                                      apiUrl:apiUrl
                                                                     xApiKey:xApiKey
                                                             crossSiteCookie:NO
                                                                cookieDomain:nil
                                                            cookieExpiration:365];
        
        // Initialize asynchronously
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            @try {
                [[MobileTracker shared] initializeWithBrandId:brandId
                                                       config:trackerConfig
                                                        error:nil];
                
                dispatch_async(dispatch_get_main_queue(), ^{
                    resolve(nil);
                });
            } @catch (NSException *exception) {
                dispatch_async(dispatch_get_main_queue(), ^{
                    reject(@"INIT_ERROR", exception.reason, nil);
                });
            }
        });
    } @catch (NSException *exception) {
        reject(@"INIT_ERROR", exception.reason, nil);
    }
}

// Track an event
RCT_EXPORT_METHOD(track:(NSString *)event
                  properties:(NSDictionary *)properties)
{
    [[MobileTracker shared] trackWithEvent:event properties:properties];
}

// Identify a user
RCT_EXPORT_METHOD(identify:(NSString *)userId
                  traits:(NSDictionary *)traits)
{
    [[MobileTracker shared] identifyWithUserId:userId traits:traits];
}

// Track a screen view
RCT_EXPORT_METHOD(screen:(NSString *)name
                  properties:(NSDictionary *)properties)
{
    [[MobileTracker shared] screenWithName:name properties:properties];
}

// Set metadata for tracking context
// Web Reference: tracker.ts lines 426-461
RCT_EXPORT_METHOD(setMetadata:(NSDictionary *)metadata
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
    @try {
        // Call the Swift method (async wrapper handles the Task internally)
        [[MobileTracker shared] setMetadataSync:metadata];
        resolve(nil);
    } @catch (NSException *exception) {
        reject(@"SET_METADATA_ERROR", exception.reason, nil);
    }
}

// Update user profile with new data
// Web Reference: tracker.ts lines 381-403
RCT_EXPORT_METHOD(set:(NSDictionary *)profileData
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
    @try {
        // Call the Swift method (async wrapper handles the Task internally)
        [[MobileTracker shared] setProfileDataSync:profileData];
        resolve(nil);
    } @catch (NSException *exception) {
        reject(@"SET_PROFILE_ERROR", exception.reason, nil);
    }
}

// Reset tracker state and clear all stored data
// Web Reference: tracker.ts lines 463-502
RCT_EXPORT_METHOD(reset:(BOOL)all)
{
    [[MobileTracker shared] resetWithAll:all];
}

// Reset tracker state (convenience method without parameters)
RCT_EXPORT_METHOD(resetDefault)
{
    [[MobileTracker shared] reset];
}

// Required for React Native to know this runs on a background thread
+ (BOOL)requiresMainQueueSetup
{
    return NO;
}

@end
